# Generated by Django 4.2.6 on 2023-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('customer', 'customer'), ('manager', 'manager'), ('staff', 'staff')], max_length=8),
        ),
    ]
