# Generated by Django 4.2.6 on 2023-10-24 10:26

import account_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0002_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=account_management.models.generate_account_number, max_length=10, unique=True),
        ),
    ]
