# Generated by Django 4.2.6 on 2023-10-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0004_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
