# Generated by Django 4.2.6 on 2023-10-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0005_alter_account_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_holder',
            new_name='user',
        ),
    ]
